# Generated by Django 4.2.7 on 2023-11-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Day_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ej_establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('number_of_reviews', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('rut', models.BigIntegerField()),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_account')),
            ],
        ),
        migrations.CreateModel(
            name='Trie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_from', models.IntegerField()),
                ('let', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['node_from', 'let'], name='api_trie_node_fr_ff2c1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.SmallIntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('establishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_open', models.TimeField()),
                ('schadule_close', models.TimeField()),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.day_week')),
                ('establishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('establishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.establishment')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.playlist'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user_account'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user_account'),
        ),
        migrations.CreateModel(
            name='Node_establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.IntegerField()),
                ('establishment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ej_establishment')),
            ],
            options={
                'indexes': [models.Index(fields=['node'], name='api_node_es_node_7f4646_idx')],
            },
        ),
    ]
