# Generated by Django 4.2.6 on 2023-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentmodel',
            name='playlist_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
